id: AA5C61AD8
base_file: f740F.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:35:57.559565
  last_modified_at: 2022-06-15 20:35:57.559571
