id: AA5C61AD8
base_file: f47B7.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:35:57.550885
  last_modified_at: 2022-06-15 20:35:57.550889
