id: AA5C61AD8
base_file: fCA1B.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:35:57.569644
  last_modified_at: 2022-06-15 20:35:57.569646
