id: AA5C61AD8
base_file: fEBD3.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:35:57.575359
  last_modified_at: 2022-06-15 20:35:57.575361
