id: AA5C61AD8
base_file: f1FB7.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:35:57.549378
  last_modified_at: 2022-06-15 20:35:57.549381
