id: AA5C61AD8
base_file: fDD4E.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:35:57.572562
  last_modified_at: 2022-06-15 20:35:57.572564
