id: AA5C61AD8
base_file: f5E59.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:35:57.552282
  last_modified_at: 2022-06-15 20:35:57.552286
