id: AA5C61AD8
base_file: fDBBF.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:35:57.570827
  last_modified_at: 2022-06-15 20:35:57.570842
